[features]
seeds = false
skip-lint = false
[programs.devnet]
swap_token = "53kTWZewdo52SxADmfHWnup92xPjw9ZgdzLNS3tDCrQq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/nisu/.config/solana/id.json"

[scripts]
test-swap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/swap-token.ts"
test-event = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/get-events.ts"

