[features]
seeds = false
skip-lint = false
[programs.localnet]
swap_token = "53kTWZewdo52SxADmfHWnup92xPjw9ZgdzLNS3tDCrQq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nisu/.config/solana/id.json"

[scripts]
test-swap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/swap-token.ts"
test-event = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/get-events.ts"
test-info = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/get-account-info.ts"

deploy = "npx ts-node migrations/create_pool.ts"
