[features]
seeds = false
skip-lint = false
[programs.devnet]
swap_token = "53kTWZewdo52SxADmfHWnup92xPjw9ZgdzLNS3tDCrQq"

# [registry]
# url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nisu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
